server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**, /transaction/**

        - id: LOAN-SERVICE
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka